{% set version = "0.4.0" %}

package:
  name: leather
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/leather/leather-{{ version }}.tar.gz
  sha256: f964bec2086f3153a6c16e707f20cb718f811f57af116075f4c0f4805c608b95

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - six >=1.6.1
  run:
    - python >=3.6
    - six >=1.6.1

test:
  imports:
    - leather
    - leather.scales
    - leather.series
    - leather.shapes
    - leather.ticks

about:
  home: https://leather.rtfd.io
  license: MIT
  license_file: COPYING
  license_family: MIT
  # license_file: COPYING - no MANIFEST - see https://docs.python.org/2/distutils/sourcedist.html#manifest-related-options
  summary: Python charting for 80% of humans.
  doc_url: https://leather.rtfd.io
  dev_url: https://github.com/wireservice/leather

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
